spring.application.name=boot-reactive-security


spring.mongodb.uri=mongodb://localhost:27017/spring-reactive-security
spring.data.mongodb.gridfs.database=files
spring.data.mongodb.gridfs.bucket=images

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false