spring.application.name=boot-reactive-security


spring.data.mongodb.uri=mongodb://localhost:27017/spring-reactive-security
spring.data.mongodb.gridfs.database=files
spring.data.mongodb.gridfs.bucket=images


spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false